# Generated by Django 5.1.3 on 2025-03-08 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0004_restaurant_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_restaurant', models.CharField(blank=True, max_length=100, null=True)),
                ('food_location', models.CharField(blank=True, max_length=100, null=True)),
                ('food_name', models.CharField(blank=True, max_length=100, null=True)),
                ('food_price', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('preparation_time', models.IntegerField(default=0)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('restaurant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='food_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('food_itemforFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodimage', to='foods.food')),
            ],
        ),
    ]
