# Generated by Django 5.1.3 on 2024-11-23 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
        ('restaurant', '0002_alter_restaurant_logo_alter_restaurant_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='restaurant_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='restaurant.restaurant'),
        ),
    ]
