# Generated by Django 5.1.3 on 2024-11-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
