# Generated by Django 5.1.3 on 2024-11-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_food_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='food_image',
        ),
    ]
