# Generated by Django 5.1.3 on 2024-11-25 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_delete_food_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodimage', to='foods.food')),
            ],
        ),
    ]
