# Generated by Django 5.1.3 on 2024-11-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_food_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_image',
            old_name='food_id',
            new_name='food_itemforFK',
        ),
    ]
