# Generated by Django 5.1.3 on 2024-11-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
